types:
  build: "Made the code better by enhancing the flow of building the distribution artefact"
  chore: "Made the code better by some housekeeping"
  ci: "Made the code better by enhancing the flow of merging/deploying additional code"
  docs: "Made the code better by writing better documentation"
  feat: "Made the code better by adding or improving a feature"
  fix: "Made the code better by fixing a bug"
  perf: "Made the code better in performance"
  refactor: "Made the code better in structure"
  revert: "Made the code better by deleting something that made the code worse"
  style: "Made the code better in style"
  test: "Made the code better by testing it better"
