dist: trusty

language: node_js

node_js:
  - node
  - lts/*

addons:
  sonarcloud:
    organization: diplomatiq

install: npm ci

script:
  - sonar-scanner
  - npm test

after_success:
  - npm run codecov
