dist: trusty

language: node_js

node_js:
  - node
  - lts/*

addons:
  sonarcloud:
    organization: diplomatiq
    token:
      secure: p9sJmjNubzbiU4q3FsEtFSLX6Z0XuU1zX4oKx5lrSEIKb4TEkLW5y/j9huJDUfLTwimNZ0ypy9pZvykmM7yVppasPk9q0qH3kqxrhhFBz1Mo4umbIZKdZf4I9svuW5ToRd7ilD7/0XkMt3jZqdz/lBC3qKQWrLEJjt1FvYzQ9e1XVoRxdczwylQa6KrtURGhtDPbOZ/ZlgppVMVc4ME0iYRbKKhpUp1wZaO/JPhiEFqkjX6rL84ZaITHzye8dOZDH8G7p9v6wUAIXkZXG6//PTdhrNCULYbwLfpB4RMQ1hI21uQkEn0uY/5r6+ULy8Txlo5sF0sG+JjAmXGoeUtvftdx4Lrbd3PjsVDJ6hF25UiTU6WWZd2eKWWTOYyukaa+DthyrEIGIfDVn7onOit5JMyr3o3cgsRpWVIRtwN1oWRZR2QlpFwlFKAj7u62H4CnnZ/kJMvKJx0R1lpqaoyy47KoNuEWE2qc5EaWXWMxxXk6ozKMlaUYsKIqf6n25P9IbGWE5pRqXdrB0EnBJfdP0lr/S6+YccRuJgjluBbeUY02Geh48W4N10OSBRaDvq0LOURFaRCeCfbbjo5wdo+FZlq3yye7Lde3zd05YRXT2L4coaKs/f9F834rUSPKJdR2Z8tH5ghI6LQnxQ6Skhget8zMTHbQivCg6gHxkpqEOpo=

install: npm ci

script:
  - commitlint-travis
  - npm run lint
  - npm run build
  - npm run test
  - sonar-scanner
