dist: trusty

language: node_js

node_js:
  - node
  - lts/*

addons:
  sonarcloud:
    organization: diplomatiq
    token:
      secure: N07KKPngs9HFx0L/Fni2mJ7I0EN0ubjc4U8IAb960dz5Mfr9PL6wvXDBcy8unkadWW0122V/KlwKanD5c+Lmw84TlNNeCPIx0ph5NsG3uBmVGhtlznpniMqeR0gPwO19IMheHMxCI2X+B8fnRwcetCUAo/Hs6sx3p6uB7sGmyeKOsnINdDx1fQjRGn3THiSf/SwGsTMoqzoazAbfh/Eu786omIp6s/wG8KRXht9rqW7lnkGeesZx7GaYsgBZYS/Na6pIiql5wVIAa+WIrKYbXgS2EsfbHi588TRqW2IKee8OdQOAo1levvr2G5v/7gu0qMwhikgYVMdPPHliBwvYL0XWoKWa8kYRbiRWk1hWUyBN2mPkrphyTdNz1JYQlaPrS0wYxZDTM8AAkqxMofw3xEUjfGl+HSTccED9iPd3orRDLXpIaMQoi0lCIn7J5swxIa9a12xFAd34cxkdJg/BABvAh/Veq/D6nyo2atQhHjvyl+ktH1Nk3/hU2NpZX6fRiZgzopp65mBhR7O3NrvzDRMF8lOrpeQLn7JnOEHUvSX+DbkIrPGtC+EWL7xSDapA9wt5jCfSG8jcoZqY7Vs2EG2ROJIhr3LOA0jHN1h8OxTDn8RxjrPZJR3+9RFKdK0mpPR/vHF1x0U0CNn6MA5ZciI1ZXXtgoWUeH66HaXMetU=

install: npm ci

script:
  - commitlint-travis
  - npm test
  - sonar-scanner
